apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: maksgovor/express-fe:latest
          imagePullPolicy: Always
          env:
            - name: BASE_URL
              value: "http://$(BACKEND_SERVICE_HOST):$(BACKEND_SERVICE_PORT)/api"
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001
