apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.19
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000